### ISSUE TITLE
Error Installation

### ISSUE THREAD

**Issue by indra-constantine** [m1stadev/PyIMG4#12]
I always get this error, on Ubuntu 22.04 with Python 3.10.4

`python3 -m pip install pyimg4
Defaulting to user installation because normal site-packages is not writeable
Collecting pyimg4
  Using cached pyimg4-0.6.3-py3-none-any.whl (11 kB)
Requirement already satisfied: click<9.0.0,>=8.0.0 in /usr/lib/python3/dist-packages (from pyimg4) (8.0.3)
Collecting pyliblzfse<0.5.0,>=0.4.1
  Using cached pyliblzfse-0.4.1.tar.gz (47 kB)
  Preparing metadata (setup.py) ... done
Collecting asn1<3.0.0,>=2.5.0
  Using cached asn1-2.6.0-py2.py3-none-any.whl (9.8 kB)
Collecting pycryptodome<4.0.0,>=3.14.1
  Using cached pycryptodome-3.15.0-cp35-abi3-manylinux2010_x86_64.whl (2.3 MB)
Collecting pylzss<0.4.0,>=0.3.1
  Using cached pylzss-0.3.1.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting enum-compat
  Using cached enum_compat-0.0.3-py3-none-any.whl (1.3 kB)
Building wheels for collected packages: pyliblzfse, pylzss
  Building wheel for pyliblzfse (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'liblzfse' extension
      creating build
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/lzfse
      creating build/temp.linux-x86_64-3.10/lzfse/src
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ilzfse/src -I/usr/include/python3.10 -c lzfse/src/lzfse_decode.c -o build/temp.linux-x86_64-3.10/lzfse/src/lzfse_decode.o -std=c99
      error: command 'x86_64-linux-gnu-gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyliblzfse
  Running setup.py clean for pyliblzfse
  Building wheel for pylzss (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'lzss' extension
      creating build
      creating build/temp.linux-x86_64-3.10
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./include -I/usr/include/python3.10 -c pylzss.c -o build/temp.linux-x86_64-3.10/pylzss.o
      error: command 'x86_64-linux-gnu-gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pylzss
  Running setup.py clean for pylzss
Failed to build pyliblzfse pylzss
Installing collected packages: pylzss, pyliblzfse, enum-compat, pycryptodome, asn1, pyimg4
  Running setup.py install for pylzss ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pylzss did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'lzss' extension
      creating build
      creating build/temp.linux-x86_64-3.10
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./include -I/usr/include/python3.10 -c pylzss.c -o build/temp.linux-x86_64-3.10/pylzss.o
      error: command 'x86_64-linux-gnu-gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pylzss

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
`

**Comment by m1stadev** [comment]
Install `build-essential` with APT.
