### ISSUE TITLE
Please update README with usage examples

### ISSUE THREAD

**Issue by doronz88** [m1stadev/PyIMG4#4]
Hi! 

I didn't quite understand how am I supposed to use it to parse a given `.im4p` image.
I saw the `examples` folder but I believe it should be available from the main CLI.
BTW, I recommend using [`click`](https://click.palletsprojects.com/en/8.1.x/) to parse the subcommands and arguments.

If you'd like, I can develop part of the CLI according to what you see fit.

**Comment by m1stadev** [comment]
Sorry for the late response, only now seeing this. I'll address some of the different things in this issue.

> I saw the `examples` folder but I believe it should be available from the main CLI.

A CLI tool is one of the main things that PyIMG4 still needs before I release a 1.0 version, and I've admittedly put it on the back-burner. I've begun work on a basic CLI tool, but still has a long way to go before being ready to be pushed to the repo.

> BTW, I recommend using [`click`](https://click.palletsprojects.com/en/8.1.x/) to parse the subcommands and arguments.

I'm still iffy on whether I want to use `click` or not, as I'd rather implement it using something in the standard library (like [`argparse`](https://docs.python.org/3/library/argparse.html))

> If you'd like, I can develop part of the CLI according to what you see fit.
Honestly, if you'd be willing I'd greatly appreciate this. I'd prefer the arguments to be similar to either [`img4tool`](https://github.com/tihmstar/img4tool) or [`img4lib`](https://github.com/xerub/img4lib), but if you have any better ideas for writing the CLI tool then I'm all ears.
